---
- name: Deploy 4team Database (RDS)
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - global_vars/all_vars
    - global_vars/secrets.yml
  roles:
    - role: roles/database